# **Assignment 7**
행렬 방정식 풀기 
---
* 다음 행렬 방정식을 'Linear Regression'를 이용해 풀어보자.
> * 적당한 learning rate를 찾아 1000 epoch 정도 계산해본다
> * 'Pseudo Inverse'를 이용한 풀이와 비교해본다
* Hint: y = wx 꼴로 변환해본다
> * Ax=B에서는 x가 미지수이지만, y=wx에서는 w가 미지수임에 주의!
> * linear model에서 b를 없애기 위해서 nn.Linear() 사용법을 검색해보자

>>>>$Ax=B$  
$A=\begin{bmatrix}
0 & 1 \\
1 & 1 \\
2 & 1 \\
3 & 1 \end{bmatrix}$, $B=\begin{bmatrix}-1 \\
0.2 \\
0.9 \\
2.1 \\ \end{bmatrix}$

In [11]:
# 라이브러리 가져오기
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as func
import torch.optim as opt

# Seed 고정
torch.manual_seed(1)

In [18]:
# Data 입력하기
A_train = torch.FloatTensor([[0,1],[1,1],[2,1],[3,1]])
B_train = torch.FloatTensor([[-1],[0.2],[0.9],[2.1]])

# 행렬 출력하기
print(A_train)
print(A_train.shape)
print(B_train)
print(B_train.shape)

# Linear model(다중 선형회귀이므로 input_dim=2, output_dim=1)
model = nn.Linear(2,1,bias=False)

# Hypothesis and cost
B_hypo = model(A_train)
print(list(model.parameters()))
print(B_hypo)

#Cost 출력하기
cost = func.mse_loss(B_hypo, B_train)
print(cost)

# Optimizer 설정
optimizer = opt.SGD(model.parameters(), lr=0.1)

#반복문 및 cost 출력하기
for epoch in range(1000):

  B_hypo = model(A_train)
  cost = func.mse_loss(B_hypo, B_train)

# cost를 이용해 model update
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 99:
    params = list(model.parameters())
    print(params)
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch+1, 1000, cost.item()
    ))

tensor([[0., 1.],
        [1., 1.],
        [2., 1.],
        [3., 1.]])
torch.Size([4, 2])
tensor([[-1.0000],
        [ 0.2000],
        [ 0.9000],
        [ 2.1000]])
torch.Size([4, 1])
[Parameter containing:
tensor([[0.6181, 0.2200]], requires_grad=True)]
tensor([[0.2200],
        [0.8382],
        [1.4563],
        [2.0744]], grad_fn=<MmBackward0>)
tensor(0.5515, grad_fn=<MseLossBackward0>)
[Parameter containing:
tensor([[ 0.9989, -0.9476]], requires_grad=True)]
Epoch  100/1000 Cost: 0.012502
[Parameter containing:
tensor([[ 1.0000, -0.9500]], requires_grad=True)]
Epoch  200/1000 Cost: 0.012500
[Parameter containing:
tensor([[ 1.0000, -0.9500]], requires_grad=True)]
Epoch  300/1000 Cost: 0.012500
[Parameter containing:
tensor([[ 1.0000, -0.9500]], requires_grad=True)]
Epoch  400/1000 Cost: 0.012500
[Parameter containing:
tensor([[ 1.0000, -0.9500]], requires_grad=True)]
Epoch  500/1000 Cost: 0.012500
[Parameter containing:
tensor([[ 1.0000, -0.9500]], requires_grad=True)]
Epoch  60